### ISSUE TITLE
Watch Error on Moving / Renaming / Deleting Files

### ISSUE THREAD

**Issue by emaildano** [roots/sage#1297]
Watch is working great now with the latest edit to browserSync but this is something that has been happening before that.

During watch if I edit / delete or rename a few php files, watch stops and it throws this error. I'm doing research now as to where it's coming from.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch ENOENT
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at Gaze._watchDir (/Users/danielolson/dev/fleisher.dev/web/app/themes/fleisher/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /Users/danielolson/dev/fleisher.dev/web/app/themes/fleisher/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/Users/danielolson/dev/fleisher.dev/web/app/themes/fleisher/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/danielolson/dev/fleisher.dev/web/app/themes/fleisher/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /Users/danielolson/dev/fleisher.dev/web/app/themes/fleisher/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/danielolson/dev/fleisher.dev/web/app/themes/fleisher/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/danielolson/dev/fleisher.dev/web/app/themes/fleisher/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
```

**Comment by austinpray** [comment]
Thank you so much for putting the 8.0.0 branch through it's paces! I'll have a look at this a bit later today.

**Comment by emaildano** [comment]
No solutions so far but here's a few related issues:

https://github.com/wearefractal/glob-watcher/issues/8
https://github.com/shama/gaze/issues/56

**Comment by trevoristall** [comment]
This is a bug with the current version of Gulp, no?
* [#71](https://github.com/gulpjs/gulp/issues/71)
* [#358](https://github.com/gulpjs/gulp/issues/358)

I've been working around this like so: 
```javascript
var origSrc = gulp.src;
gulp.src = function () {
    return fixPipe(origSrc.apply(this, arguments));
};
function fixPipe(stream) {
    var origPipe = stream.pipe;
    stream.pipe = function (dest) {
        arguments[0] = dest.on('error', function (error) {
            var nextStreams = dest._nextStreams;
            if (nextStreams) {
                nextStreams.forEach(function (nextStream) {
                    nextStream.emit('error', error);
                });
            } else if (dest.listeners('error').length === 1) {
                throw error;
            }
        });
        var nextStream = fixPipe(origPipe.apply(this, arguments));
        (this._nextStreams || (this._nextStreams = [])).push(nextStream);
        return nextStream;
    };
    return stream;
}
```
Add it to your gulpfile.js and use it like this:
```javascript
    gulp.src(src)
        // stuff...
        .pipe(uglify({compress: {}}))
        .pipe(gulp.dest('./dist'))
        .on('error', function (error) {
            console.error('' + error);
        });
```

**Comment by austinpray** [comment]
@trevoristall looking at the source for your snippet and https://github.com/floatdrop/gulp-plumber aren't they doing sort of the same thing?

**Comment by trevoristall** [comment]
You are correct, they are both trying to fix the same problem. My Experience with gulp plumber was that it was breaking several other plugins. That was several months ago though and I haven't tried it since.

**Comment by drawcard** [comment]
Getting a similar error when attempting to run ```gulp build```:

```
04:11 $ gulp build
[04:11:53] Using gulpfile /var/www/clients/drawcard.com.au/wp-content/themes/build/gulpfile.js
[04:11:53] Starting 'styles'...
[04:12:06] Starting 'jshint'...
[04:12:08] Starting 'fonts'...
[04:12:09] Starting 'images'...
[04:12:34] Finished 'jshint' after 29 s
[04:12:34] Starting 'scripts'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by kalenjohnson** [comment]
I haven't seen this issue over two projects. Anyone else seeing it still?

**Comment by emaildano** [comment]
I'm still getting this error running on the latest build.

![screen shot 2015-04-02 at 11 59 43 am](https://cloud.githubusercontent.com/assets/1872327/6967822/f86ae266-d92f-11e4-871c-be7dadb98b7d.png)

**Comment by retlehs** [comment]
https://stackoverflow.com/questions/22391527/gulps-gulp-watch-not-triggered-for-new-or-deleted-files

**Comment by retlehs** [comment]
dang this is old. focus is on sage 9 right now
