### ISSUE TITLE
probleme with images folder

### ISSUE THREAD

**Issue by melt-cdk** [roots/sage#1400]
Hello,

when i upload a images in my assets/images folder and i run gulp. i hve this error : 
```
child_process.js:1155
    throw errnoException(err, 'spawn');
          ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at exports.execFile (child_process.js:682:15)
    at ExecBuffer.<anonymous> (/Users/tmerle/Dropbox/Persos/Project/eip-online/eip2015/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/exec-buffer/index.js:91:3)
    at /Users/tmerle/Dropbox/Persos/Project/eip-online/eip2015/node_modules/wiredep/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:99:15)
```

Process limit ?

osx yosemite
npm 2.7.4
node 0.12

tx

**Comment by lautreamont3** [comment]
Maybe you have to change file permissions. Don't have OSX but when I get EACESS error usually are file permissions.

**Comment by mAAdhaTTah** [comment]
Delete your `node_modules` folder and re-run `npm install` and see if you still get the error. Also check the perms on your `~/.npm` folder.

**Comment by mAAdhaTTah** [comment]
Maybe also check the perms on the images you just uploaded too.

**Comment by austinpray** [comment]
Check the folder and file permissions.

If you are still having trouble after verifying the correct file permissions, post a thread over on https://discourse.roots.io/
