### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by SNeilson** [roots/sage#1525]
We've been using Sage for a few months without issue but now when we try to run gulp watch we get this error

SyntaxError: Unexpected token }
    at Object.parse (native)
    at module.exports (C:\wamp\www\multisite\wp-content\themes\imgtec\node_modules\asset-builder\lib\readManifest.js:19:15)
    at new module.exports (C:\wamp\www\multisite\wp-content\themes\imgtec\node_modules\asset-builder\lib\Manifest.js:28:34)
    at module.exports (C:\wamp\www\multisite\wp-content\themes\imgtec\node_modules\asset-builder\index.js:17:10)
    at Object.<anonymous> (C:\wamp\www\multisite\wp-content\themes\imgtec\gulpfile.js:11:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Does anyone have any ideas how we fix this because as far as we can tell nothing changed?

**Comment by mAAdhaTTah** [comment]
Did your bower.json file change? Looks like it could be a syntax error there.

**Comment by swalkinshaw** [comment]
If this were a bug it would be over at https://github.com/austinpray/asset-builder
