### ISSUE TITLE
NPM install produce error

### ISSUE THREAD

**Issue by ferry77** [roots/sage#1542]
Hi, I want to try sage and when doing NPM install I got below error.. 
I found from other post it may need to use Nan2 https://github.com/nodejs/nan/issues/451
Any help appreciated.

Thanks

===========================================================
npm install

> bufferutil@1.1.0 install /Users/myname/code/sage/wp-content/themes/sage-child/node_modules/bufferutil
> node-gyp rebuild

CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
    ^
    ../node_modules/nan/nan.h:256:25: note: previous definition is here
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
        ^
        ../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
        'node'
        , node::smalloc::FreeCallback callback
        ~~~~~~^
        ../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
        return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
        ^~~~~~~~~~~~~~~~~
        /Users/myname/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note:
        candidate function not viable: no known conversion from 'uint32_t'
        (aka 'unsigned int') to 'enum encoding' for 3rd argument
        NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
          ^
          /Users/myname/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note:
          candidate function not viable: 2nd argument ('const char *') would lose
          const qualifier
          NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
            ^
            /Users/myname/.node-gyp/4.1.0/include/node/node_buffer.h:28:40: note:
            candidate function not viable: requires 2 arguments, but 3 were provided
            NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
              ^
              /Users/myname/.node-gyp/4.1.0/include/node/node_buffer.h:36:40: note:
              candidate function not viable: requires 5 arguments, but 3 were provided
              NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                ^
                In file included from ../src/bufferutil.cc:16:
                ../node_modules/nan/nan.h:676:12: error: no viable conversion from
                'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
                    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    /Users/myname/.node-gyp/4.1.0/include/node/v8.h:210:7: note: candidate
                    constructor (the implicit copy constructor) not viable: no known
                    conversion from 'v8::MaybeLocal<v8::Object>' to 'const
                      v8::Local<v8::Object> &' for 1st argument
                        class Local {
                        ^
                        /Users/myname/.node-gyp/4.1.0/include/node/v8.h:210:7: note: candidate
                        constructor (the implicit move constructor) not viable: no known
                        conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&'
                            for 1st argument
                            class Local {
                            ^
                            /Users/myname/.node-gyp/4.1.0/include/node/v8.h:214:13: note: candidate
                            template ignored: could not match 'Local' against 'MaybeLocal'
                            V8_INLINE Local(Local<S> that)
                              ^
                              /Users/myname/.node-gyp/4.1.0/include/node/v8.h:326:13: note: candidate
                              template ignored: could not match 'S *' against
                              'v8::MaybeLocal<v8::Object>'
                                V8_INLINE Local(S* that)
                                ^
                                In file included from ../src/bufferutil.cc:16:
                                ../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
                                'node::Buffer'
                                return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
                                ~~~~~~~~~~~~~~^
                                In file included from ../src/bufferutil.cc:7:
                                /Users/myname/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to
                                'v8::Primitive *volatile' from incompatible type 'v8::Value *'
                                TYPE_CHECK(T, S);
                                ^~~~~~~~~~~~~~~~
                                /Users/myname/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded
                                from macro 'TYPE_CHECK'
                                *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                ^ ~~~~~~~~~~~~~~~~~~
                                ../node_modules/nan/nan.h:414:12: note: in instantiation of function template
                                specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
                                    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
                                    ^
                                    ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
                                    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                    ^
                                    In file included from ../src/bufferutil.cc:7:
                                    /Users/myname/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to
                                    'v8::Boolean *volatile' from incompatible type 'v8::Value *'
                                    TYPE_CHECK(T, S);
                                    ^~~~~~~~~~~~~~~~
                                    /Users/myname/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded
                                    from macro 'TYPE_CHECK'
                                    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
                                    ../node_modules/nan/nan.h:424:12: note: in instantiation of function template
                                    specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
                                        return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
                                        ^
                                        ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
                                        # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                        ^
                                        In file included from ../src/bufferutil.cc:7:
                                        /Users/myname/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to
                                        'v8::Function *volatile' from incompatible type 'v8::Value *'
                                        TYPE_CHECK(T, S);
                                        ^~~~~~~~~~~~~~~~
                                        /Users/myname/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded
                                        from macro 'TYPE_CHECK'
                                        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
                                        ../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
                                        specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
                                            return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
                                            ^
                                            ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
                                            # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                            ^
                                            In file included from ../src/bufferutil.cc:7:
                                            /Users/myname/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to
                                            'v8::Object *volatile' from incompatible type 'v8::Value *'
                                            TYPE_CHECK(T, S);
                                            ^~~~~~~~~~~~~~~~
                                            /Users/myname/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded
                                            from macro 'TYPE_CHECK'
                                            *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                            ^ ~~~~~~~~~~~~~~~~~~
                                            ../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
                                            specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
                                                return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
                                                  ^
                                                  ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
                                                  # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                                  ^
                                                  9 errors generated.
                                                  make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
                                                  gyp ERR! build error
                                                  gyp ERR! stack Error: `make` failed with exit code: 2
                                                  gyp ERR! stack     at ChildProcess.onExit (/Users/myname/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
                                                  gyp ERR! stack     at emitTwo (events.js:87:13)
                                                  gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
                                                  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
                                                  gyp ERR! System Darwin 14.5.0
                                                  gyp ERR! command "/usr/local/bin/node" "/Users/myname/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
                                                  gyp ERR! cwd /Users/myname/code/sage/wp-content/themes/sage-child/node_modules/bufferutil
                                                  gyp ERR! node -v v4.1.0
                                                  gyp ERR! node-gyp -v v3.0.1
                                                  gyp ERR! not ok
                                                  npm WARN install:bufferutil bufferutil@1.1.0 install: `node-gyp rebuild`
                                                  npm WARN install:bufferutil Exit status 1

                                                  > utf-8-validate@1.1.0 install /Users/myname/code/sage/wp-content/themes/sage-child/node_modules/utf-8-validate
                                                  > node-gyp rebuild

                                                  CXX(target) Release/obj.target/validation/src/validation.o
                                                  In file included from ../src/validation.cc:15:
                                                  ../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
                                                  NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                                                      ^
                                                      ../node_modules/nan/nan.h:256:25: note: previous definition is here
                                                      NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                                                          ^
                                                          ../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
                                                          'node'
                                                          , node::smalloc::FreeCallback callback
                                                          ~~~~~~^
                                                          ../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
                                                          return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                          ^~~~~~~~~~~~~~~~~
                                                          /Users/myname/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note:
                                                          candidate function not viable: no known conversion from 'uint32_t'
                                                          (aka 'unsigned int') to 'enum encoding' for 3rd argument
                                                          NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                                            ^
                                                            /Users/myname/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note:
                                                            candidate function not viable: 2nd argument ('const char *') would lose
                                                            const qualifier
                                                            NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                                              ^
                                                              /Users/myname/.node-gyp/4.1.0/include/node/node_buffer.h:28:40: note:
                                                              candidate function not viable: requires 2 arguments, but 3 were provided
                                                              NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                                                ^
                                                                /Users/myname/.node-gyp/4.1.0/include/node/node_buffer.h:36:40: note:
                                                                candidate function not viable: requires 5 arguments, but 3 were provided
                                                                NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                                                  ^
                                                                  In file included from ../src/validation.cc:15:
                                                                  ../node_modules/nan/nan.h:676:12: error: no viable conversion from
                                                                  'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
                                                                      return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                      /Users/myname/.node-gyp/4.1.0/include/node/v8.h:210:7: note: candidate
                                                                      constructor (the implicit copy constructor) not viable: no known
                                                                      conversion from 'v8::MaybeLocal<v8::Object>' to 'const
                                                                        v8::Local<v8::Object> &' for 1st argument
                                                                          class Local {
                                                                          ^
                                                                          /Users/myname/.node-gyp/4.1.0/include/node/v8.h:210:7: note: candidate
                                                                          constructor (the implicit move constructor) not viable: no known
                                                                          conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&'
                                                                              for 1st argument
                                                                              class Local {
                                                                              ^
                                                                              /Users/myname/.node-gyp/4.1.0/include/node/v8.h:214:13: note: candidate
                                                                              template ignored: could not match 'Local' against 'MaybeLocal'
                                                                              V8_INLINE Local(Local<S> that)
                                                                                ^
                                                                                /Users/myname/.node-gyp/4.1.0/include/node/v8.h:326:13: note: candidate
                                                                                template ignored: could not match 'S *' against
                                                                                'v8::MaybeLocal<v8::Object>'
                                                                                  V8_INLINE Local(S* that)
                                                                                  ^
                                                                                  In file included from ../src/validation.cc:15:
                                                                                  ../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
                                                                                  'node::Buffer'
                                                                                  return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
                                                                                  ~~~~~~~~~~~~~~^
                                                                                  In file included from ../src/validation.cc:7:
                                                                                  /Users/myname/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to
                                                                                  'v8::Primitive *volatile' from incompatible type 'v8::Value *'
                                                                                  TYPE_CHECK(T, S);
                                                                                  ^~~~~~~~~~~~~~~~
                                                                                  /Users/myname/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded
                                                                                  from macro 'TYPE_CHECK'
                                                                                  *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                                                                  ^ ~~~~~~~~~~~~~~~~~~
                                                                                  ../node_modules/nan/nan.h:414:12: note: in instantiation of function template
                                                                                  specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
                                                                                      return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
                                                                                      ^
                                                                                      ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
                                                                                      # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                                                                      ^
                                                                                      In file included from ../src/validation.cc:7:
                                                                                      /Users/myname/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to
                                                                                      'v8::Boolean *volatile' from incompatible type 'v8::Value *'
                                                                                      TYPE_CHECK(T, S);
                                                                                      ^~~~~~~~~~~~~~~~
                                                                                      /Users/myname/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded
                                                                                      from macro 'TYPE_CHECK'
                                                                                      *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                                                                      ^ ~~~~~~~~~~~~~~~~~~
                                                                                      ../node_modules/nan/nan.h:424:12: note: in instantiation of function template
                                                                                      specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
                                                                                          return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
                                                                                          ^
                                                                                          ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
                                                                                          # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                                                                          ^
                                                                                          In file included from ../src/validation.cc:7:
                                                                                          /Users/myname/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to
                                                                                          'v8::Function *volatile' from incompatible type 'v8::Value *'
                                                                                          TYPE_CHECK(T, S);
                                                                                          ^~~~~~~~~~~~~~~~
                                                                                          /Users/myname/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded
                                                                                          from macro 'TYPE_CHECK'
                                                                                          *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                                                                          ^ ~~~~~~~~~~~~~~~~~~
                                                                                          ../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
                                                                                          specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
                                                                                              return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
                                                                                              ^
                                                                                              ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
                                                                                              # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                                                                              ^
                                                                                              In file included from ../src/validation.cc:7:
                                                                                              /Users/myname/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to
                                                                                              'v8::Object *volatile' from incompatible type 'v8::Value *'
                                                                                              TYPE_CHECK(T, S);
                                                                                              ^~~~~~~~~~~~~~~~
                                                                                              /Users/myname/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded
                                                                                              from macro 'TYPE_CHECK'
                                                                                              *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                                                                              ^ ~~~~~~~~~~~~~~~~~~
                                                                                              ../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
                                                                                              specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
                                                                                                  return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
                                                                                                    ^
                                                                                                    ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
                                                                                                    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                                                                                    ^
                                                                                                    9 errors generated.
                                                                                                    make: *** [Release/obj.target/validation/src/validation.o] Error 1
                                                                                                    gyp ERR! build error
                                                                                                    gyp ERR! stack Error: `make` failed with exit code: 2
                                                                                                    gyp ERR! stack     at ChildProcess.onExit (/Users/myname/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
                                                                                                    gyp ERR! stack     at emitTwo (events.js:87:13)
                                                                                                    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
                                                                                                    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
                                                                                                    gyp ERR! System Darwin 14.5.0
                                                                                                    gyp ERR! command "/usr/local/bin/node" "/Users/myname/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
                                                                                                    gyp ERR! cwd /Users/myname/code/sage/wp-content/themes/sage-child/node_modules/utf-8-validate
                                                                                                    gyp ERR! node -v v4.1.0
                                                                                                    gyp ERR! node-gyp -v v3.0.1
                                                                                                    gyp ERR! not ok
                                                                                                    npm WARN install:utf-8-validate utf-8-validate@1.1.0 install: `node-gyp rebuild`
                                                                                                    npm WARN install:utf-8-validate Exit status 1

                                                                                                    > fsevents@0.3.8 install /Users/myname/code/sage/wp-content/themes/sage-child/node_modules/fsevents
                                                                                                    > node-gyp rebuild

                                                                                                    SOLINK_MODULE(target) Release/.node
                                                                                                    ld: library not found for -lgcc_s.10.5
                                                                                                    clang: error: linker command failed with exit code 1 (use -v to see invocation)
                                                                                                    make: *** [Release/.node] Error 1
                                                                                                    gyp ERR! build error
                                                                                                    gyp ERR! stack Error: `make` failed with exit code: 2
                                                                                                    gyp ERR! stack     at ChildProcess.onExit (/Users/myname/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
                                                                                                    gyp ERR! stack     at emitTwo (events.js:87:13)
                                                                                                    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
                                                                                                    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
                                                                                                    gyp ERR! System Darwin 14.5.0
                                                                                                    gyp ERR! command "/usr/local/bin/node" "/Users/myname/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
                                                                                                    gyp ERR! cwd /Users/myname/code/sage/wp-content/themes/sage-child/node_modules/fsevents
                                                                                                    gyp ERR! node -v v4.1.0
                                                                                                    gyp ERR! node-gyp -v v3.0.1
                                                                                                    gyp ERR! not ok

                                                                                                    npm ERR! Darwin 14.5.0
                                                                                                    npm ERR! argv "/usr/local/bin/node" "/Users/myname/.npm-packages/bin/npm" "install"
                                                                                                    npm ERR! node v4.1.0
                                                                                                    npm ERR! npm  v3.3.3
                                                                                                    npm ERR! code ELIFECYCLE
                                                                                                    npm ERR! fsevents@0.3.8 install: `node-gyp rebuild`
                                                                                                    npm ERR! Exit status 1
                                                                                                    npm ERR!
                                                                                                    npm ERR! Failed at the fsevents@0.3.8 install script 'node-gyp rebuild'.
                                                                                                    npm ERR! This is most likely a problem with the fsevents package,
                                                                                                    npm ERR! not with npm itself.
                                                                                                    npm ERR! Tell the author that this fails on your system:
                                                                                                    npm ERR!     node-gyp rebuild
                                                                                                    npm ERR! You can get their info via:
                                                                                                    npm ERR!     npm owner ls fsevents
                                                                                                    npm ERR! There is likely additional logging output above.

**Comment by retlehs** [comment]
see https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060
