### ISSUE TITLE
npm install > exiting

### ISSUE THREAD

**Issue by abumalick** [roots/sage#1547]
Hello,
I am running  winsows 10 and while running npm install, the install exits because it failed to rename a file.
Here are the logs:
````
C:\xampp\htdocs\forqane>node -v && npm -v && gulp -v
v0.12.7
2.11.3
[20:35:51] CLI version 3.9.0

C:\xampp\htdocs\forqane>npm install
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
|
> jpegtran-bin@3.0.4 postinstall C:\xampp\htdocs\forqane\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\xampp\htdocs\bedrock\web\app\themes\forqane\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\buffer-to-vinyl\node_modules\readable-stream\lib\_stream_duplex.js:20:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm WARN optional dep failed, continuing imagemin-jpegtran@4.3.0
-


> spawn-sync@1.0.13 postinstall C:\xampp\htdocs\forqane\node_modules\gulp-sass\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

-
> node-sass@3.3.3 install C:\xampp\htdocs\forqane\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\xampp\htdocs\bedrock\web\app\themes\forqane\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-14\binding.node

> node-sass@3.3.3 postinstall C:\xampp\htdocs\forqane\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

` C:\xampp\htdocs\bedrock\web\app\themes\forqane\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-14\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path C:\Users\abdul\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, rename 'C:\Users\abdul\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, rename 'C:\Users\abdul\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\abdul\\AppData\\Roaming\\npm-cache\\inherits\\2.0.1\\package\\package.json',
npm ERR!   parent: 'glob' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\forqane\npm-debug.log
````
The file C:\Users\abdul\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json
actually exists.
Note: C:\xampp\htdocs\forqane\ is actually a symlink to the real theme. I use this because I get "path too long" errors while running npm install from full path.

After this: Running bower install worked very well
And running gulp I get : 
Error: Cannot find module 'browser-sync'

I don't realy understant what's the problem. Your help is welcome

**Comment by escobar022** [comment]
It is possible that you have a cached node module. This was the case for me after updating npm.  clearing the cache for npm might help this issue. ( rm -rf ~/.cache/* on Mac )

**Comment by abumalick** [comment]
I don't think so. 
I ran npm cache clear before install
I deleted node_modules too before install by the way

**Comment by QWp6t** [comment]
Yeah, I'd get rimraf and delete node_modules and .cache.

```
npm install -g rimraf
rimraf .\node_modules "%appdata%\npm-cache"
```

**Comment by QWp6t** [comment]
To be clear, `rimraf` aggressively removes a directory tree. Its name is derived from `rm -rf`, if you're familiar with that.

Its primary use case is removing npm stuff on Windows because Windows always balks at the long directory names. `rimraf` manages to get around those errors and deletes deeply nested npm paths.

Just wanted to make it clear what it does so you understand there's a certain risk to using it. Make sure you're putting in paths you actually want removed, and use hard coded absolute paths if you want to be extra cautious.

**Comment by abumalick** [comment]
Thank you for the tip, I wanted rm -rf in windows :+1: 
Running now:
rimraf .\node_modules "%appdata%\npm-cache"

and then
npm install
Another error:
````
> node-sass@3.3.3 postinstall C:\xampp\htdocs\forqane\node_modules\gulp-sass\node_modules\node-sass

> node scripts/build.js

` C:\xampp\htdocs\bedrock\web\app\themes\forqane\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-14\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\abdul\AppData\Local\Temp\npm-4164-8a225b19\registry.npmjs.org\browser-sync-ui\-\browser-sync-ui-0.5.16.tgz
npm ERR! Expected: e08b5fb1d5c7587e996f815c4c5e7e4c2532f2e8
npm ERR! Actual:   403d76bd28f0777effc8988a7dedb4e5cde09933
npm ERR! From:     https://registry.npmjs.org/browser-sync-ui/-/browser-sync-ui-0.5.16.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\forqane\npm-debug.log
````
Removed everything in C:\Users\abdul\AppData\Local\Temp\npm-*
rimraf .\node_modules "%appdata%\npm-cache"
npm install
...
same error.
How can I fix that?
Support greatly appreciated

**Comment by abumalick** [comment]
npm install browser-sync-ui
npm install
(passed with some warning)
bower install
gulp
