### ISSUE TITLE
$ gulp failing

### ISSUE THREAD

**Issue by entr** [roots/sage#1596]
Sage 8.4.0 (installed from zip)

This is happening on a vagrant box (virtualbox), if relevant.

```log
$ npm -v
3.5.2
```

```log
$ npm i
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

```log
$ gulp
module.js:340
    throw err;
    ^

Error: Cannot find module './source-map/source-map-generator'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/www/web/app/themes/sage/node_modules/gulp-autoprefixer/node_modules/postcss/node_modules/source-map/lib/source-map.js:6:30)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

```log
$ uname -a
Linux 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Am I missing something? Also is it only me or this gulp configuration is huuuuge, nothing took that long to install.

**Comment by entr** [comment]
After downgrading `node` to `0.12.x` I was able to build. Maybe `npm` setup needs some love to make it compatible with `node 4.x`
