### ISSUE TITLE
backtick syntax in webpack requires nodejs >= 4.x (not 0.12)

### ISSUE THREAD

**Issue by martin-rueegg** [roots/sage#1730]
[webpack.config.js:42](https://github.com/roots/sage/blob/953a8ab5d63b5f484da5b6fbef155aa22bc2effa/assets/build/webpack.config.js#L42) is causing a compile error if nodejs does not meet the requirements. Since standard nodejs version shipped with el7 is 0.10, a neat error message would be fantastic! :-)
- [x] I've read the [guidelines for Contributing to Roots Projects]
- [ ] This is a feature request (it depends)
- [x] This is a bug report (it depends)
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
  - https://github.com/roots/sage/search?q=backtick&type=Issues&utf8=%E2%9C%93
  - https://github.com/roots/sage/search?q=Unexpected+token+ILLEGAL&type=Issues
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request

---

**What is the current behavior?**

`npm run build` fails at webpack with `Unexpected token ILLEGAL`

```
]# npm run build

> sage@9.0.0-alpha.3 build /home/bristolpound/preview.bristolpound.org/web/app/themes/bristolpound_2016
> webpack --progress --config assets/build/webpack.config.js

/home/bristolpound/preview.bristolpound.org/web/app/themes/bristolpound_2016/assets/build/webpack.config.js:42
    filename: `scripts/${assetsFilenames}.js`,
              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/home/bristolpound/preview.bristolpound.org/web/app/themes/bristolpound_2016/node_modules/webpack/bin/convert-argv.js:93:13)
    at Object.<anonymous> (/home/bristolpound/preview.bristolpound.org/web/app/themes/bristolpound_2016/node_modules/webpack/bin/webpack.js:135:40)
    at Module._compile (module.js:460:26)

npm ERR! Linux 4.4.11-x1-64+
npm ERR! argv "node" "/usr/bin/npm" "run" "build"
npm ERR! node v0.12.16
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sage@9.0.0-alpha.3 build: `webpack --progress --config assets/build/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sage@9.0.0-alpha.3 build script 'webpack --progress --config assets/build/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --config assets/build/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bristolpound/preview.bristolpound.org/web/app/themes/bristolpound_2016/npm-debug.log
```

**What is the expected or desired behavior?**
- [ ] version check in build script?
- update documentation to require node.js >= 4.x
  - [x] https://github.com/roots/sage/blob/master/README.md (correct)
  - [ ] https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060

---
## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

```
# composer -V
Composer version 1.1.1 2016-05-17 12:25:44

# composer create-project roots/sage your-theme-name dev-master
Installing roots/sage (dev-master a87cd047ccc3763c32ec33a9c9a6448632a31c6c)
  - Installing roots/sage (dev-master master)
    Cloning master

Created project in your-theme-name
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing composer/installers (v1.0.23)
    Loading from cache

  - Installing symfony/filesystem (v3.0.4)
    Loading from cache

  - Installing symfony/dependency-injection (v3.0.4)
    Loading from cache

  - Installing symfony/config (v3.0.4)
    Loading from cache

  - Installing pdepend/pdepend (2.2.4)
    Loading from cache

  - Installing phpmd/phpmd (2.4.2)
    Loading from cache

  - Installing squizlabs/php_codesniffer (2.5.1)
    Loading from cache

symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/dependency-injection suggests installing symfony/yaml ()
symfony/config suggests installing symfony/yaml (To use the yaml reference dumper)
Generating autoload files
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]?

# npm cache clear && rm -rf node_modules && npm install
# npm run build

> sage@9.0.0-alpha.3 build /home/user/your-theme-name
> webpack --progress --config assets/build/webpack.config.js

/home/bristolpound/your-theme-name/assets/build/webpack.config.js:42
    filename: `scripts/${assetsFilenames}.js`,
              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/usr/lib/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/lib/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:460:26)

npm ERR! Linux 4.4.11-x1-64+
npm ERR! argv "node" "/usr/bin/npm" "run" "build"
npm ERR! node v0.12.16
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sage@9.0.0-alpha.3 build: `webpack --progress --config assets/build/webpack.config.js`
npm ERR! Exit status 1

# sudo yum remove nodejs
# sudo yum remove nodesource-release.noarch
# curl -sL https://rpm.nodesource.com/setup_4.x | sudo bash -
# npm cache clear && rm -rf node_modules && npm install
# node -v && npm -v && gulp -v && bower -v && webpack
v4.6.0
2.15.9
[23:13:32] CLI version 3.9.1
1.7.9

# npm run build

> sage@9.0.0-alpha.3 build /home/user/your-theme-name
> webpack --progress --config assets/build/webpack.config.js

clean-w 10% building modules 3/7 modules 4 Hash: 2d4f335ef1a79ffe0ac8                                                             Version: webpack 2.1.0-beta.22
Time: 21409ms
                                    Asset       Size  Chunks             Chunk Names
                    scripts/customizer.js  798 bytes       1  [emitted]  customizer
  vendor/fontawesome-webfont_25a32416.eot    76.5 kB          [emitted]
  vendor/fontawesome-webfont_1dc35d25.ttf     153 kB          [emitted]
vendor/fontawesome-webfont_e6cf7c6e.woff2    71.9 kB          [emitted]
 vendor/fontawesome-webfont_c8ddf1e5.woff    90.4 kB          [emitted]
                          scripts/main.js    72.5 kB       0  [emitted]  main
  vendor/fontawesome-webfont_d7c63908.svg   41 bytes          [emitted]
                         scripts/files.js  578 bytes       2  [emitted]  files
                          styles/main.css     194 kB       0  [emitted]  main
                      scripts/main.js.map     401 kB       0  [emitted]  main
                      styles/main.css.map     468 kB       0  [emitted]  main
                scripts/customizer.js.map    7.91 kB       1  [emitted]  customizer
                     scripts/files.js.map    6.02 kB       2  [emitted]  files
  [12] multi customizer 40 bytes {1} [built]
  [13] multi files 16 bytes {2} [built]
  [14] multi main 52 bytes {0} [built]
    + 12 hidden modules
Child extract-text-webpack-plugin:
                                        Asset     Size  Chunks             Chunk Names
      vendor/fontawesome-webfont_25a32416.eot  76.5 kB          [emitted]
      vendor/fontawesome-webfont_1dc35d25.ttf   153 kB          [emitted]
    vendor/fontawesome-webfont_e6cf7c6e.woff2  71.9 kB          [emitted]
     vendor/fontawesome-webfont_c8ddf1e5.woff  90.4 kB          [emitted]
        + 8 hidden modules
```

**Please describe your local environment:**

WordPress version: 4.6.1

OS: CentOS Linux release 7.2.1511 (Core)
Linux 4.4.11-x1-64+ #1 SMP Fri May 20 14:04:36 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

NPM/Node version:

```
# node -v && npm -v && gulp -v && bower -v && webpack
v0.12.16
3.10.8
[22:11:57] CLI version 3.9.1
1.7.9
webpack 1.13.2
```

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**
- [x] https://discourse.roots.io/search?q=Unexpected%20token%20ILLEGAL
- [x] 

---
## Feature Request

**Please provide use cases for changing the current behavior:**

Standard nodejs version shipped with el7 is 0.10. So a neat error message would be amazing!

**Other relevant information:**
- https://github.com/nodesource/distributions could me mentioned.

**Comment by retlehs** [comment]
i updated the npm debugging guidelines thread you linked with the new node version requirements, thanks for pointing that out
