### ISSUE TITLE
Call to undefined function Illuminate\Support\mb_strpos()

### ISSUE THREAD

**Issue by coderste** [roots/sage#1921]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

## Bug report

I install sage the recommended way with Composer and Bedrock but when I activate the theme I get the following message

`
Fatal error: Uncaught Error: Call to undefined function Illuminate\Support\mb_strpos() in /var/www/html/web/app/themes/crafted-themes/vendor/illuminate/support/Str.php:72 Stack trace: #0 /var/www/html/web/app/themes/crafted-themes/vendor/illuminate/view/Compilers/BladeCompiler.php(285): Illuminate\Support\Str::contains('extends', '@') #1 /var/www/html/web/app/themes/crafted-themes/vendor/illuminate/view/Compilers/BladeCompiler.php(272): Illuminate\View\Compilers\BladeCompiler->compileStatement(Array) #2 [internal function]: Illuminate\View\Compilers\BladeCompiler->Illuminate\View\Compilers\{closure}(Array) #3 /var/www/html/web/app/themes/crafted-themes/vendor/illuminate/view/Compilers/BladeCompiler.php(273): preg_replace_callback('/\\B@(@?\\w+(?:::...', Object(Closure), '@extends('layou...') #4 /var/www/html/web/app/themes/crafted-themes/vendor/illuminate/view/Compilers/BladeCompiler.php(240): Illuminate\View\Compilers\BladeCompiler->compileStatements('@extends('layou...') #5 /var/www/html/web/app/themes/crafted-themes/ve in /var/www/html/web/app/themes/crafted-themes/vendor/illuminate/support/Str.php on line 72`

**Please describe your local environment:**

WordPress version: 4.8

OS: macOX

NPM/Node version: v6.10.3

**Where did the bug happen? Development or remote servers?**

Development Server

**Comment by coderste** [comment]
Wait close this issue - turns out I did not have php-mbstring installed on my server
