### ISSUE TITLE
WooCommerce reviews conflict

### ISSUE THREAD

**Issue by evertsemeijn** [roots/sage#2028]
## Submit a feature request or bug report
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums
---

**What is the current behavior?**
Error on single products

**What is the expected or desired behavior?**
Show single product
---
## Bug report
**Please provide steps to reproduce, including full log output:**

1. Install, activate, setup WooCommerce;
2. WooCommerce > Settings > Products > 'Enable product reviews'

Output:
`Fatal error: Uncaught InvalidArgumentException: Unrecognized extension in file: reviews in /app/public/wp-content/themes/xxxxxx/vendor/illuminate/view/Factory.php:258 Stack trace: #0 /app/public/wp-content/themes/xxxxxx/vendor/illuminate/view/Factory.php(227): Illuminate\View\Factory->getEngineFromPath('reviews') #1 /app/public/wp-content/themes/xxxxxx/vendor/illuminate/view/Factory.php(112): Illuminate\View\Factory->viewInstance('reviews', 'reviews', Array) #2 [internal function]: Illuminate\View\Factory->file('reviews', Array, Array) #3 /app/public/wp-content/themes/xxxxxx/vendor/roots/sage-lib/Template/Blade.php(138): call_user_func_array(Array, Array) #4 /app/public/wp-content/themes/xxxxxx/vendor/roots/sage-lib/Template/Blade.php(69): Roots\Sage\Template\Blade->__call('file', Array) #5 /app/public/wp-content/themes/xxxxxx/app/helpers.php(70): Roots\Sage\Template\Blade->compiledPath('reviews', Array) #6 /app/public/wp-content/themes/xxxxxx/app/filters.php( in /app/public/wp-content/themes/xxxxxx/vendor/illuminate/view/Factory.php on line 258 `

Disabling product reviews fixed it.

**Please describe your local environment:**

WordPress version: 4.9.4
WooCommerce version: 3.3.1

OS: -

NPM/Node version: 8.9.4

**Where did the bug happen? Development or remote servers?**
Both

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

None

**Comment by hambos22** [comment]
I confirm this bug.

**Comment by QWp6t** [comment]
Increase priority on `comments_template` filter.

**app/filters.php**
```diff
 add_filter('comments_template', function ($comments_template) {
 //...
-});
+, 100);

**Comment by intositeme** [comment]
I confirm this bug. @QWp6t suggestion fixed this.
