### ISSUE TITLE
Sage10 dev-master: open_basedir restriction in effect. File(/) is not within the allowed path

### ISSUE THREAD

**Issue by sgatz** [roots/sage#2677]
* [X ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
On a fresh new theme of Sage 10 from dev-master when I deploy it to a live server (AWS EC2) using Trellis/Bedrock, then either activate it or preview it, you get this error: 

```
production.ERROR: is_writable(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/srv/www/:/tmp) {"exception":"[object] (ErrorException(code: 0): is_writable(): open_basedir restriction in effect. File(/) is not within the allowed path(s):
```  

Other non-sage themes work in this environment, and a fresh install of a sage9 theme works also.   I can also turn off open_basedir, but that's not ideal.   See full stack trace at bottom.   I've tried disabling all plugins, still same error.  Non sage plugins work, sage9 works.

## Steps to reproduce
1.  create new theme: composer create-project roots/sage your-theme-name dev-master
2. yarn, yarn build, checkin.   
3. integate into build-before.yml
4. deploy to server
5. go to wp admin > appearance > preview this theme OR activate and go to home page of theme 

**Expected behavior:**
Expected theme to render

**Actual behavior:** 
White screens with above error in storage/logs

**Reproduces how often:** 
100% reproducible.  tried on my custom theme and then a fresh install of dev-master

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

## Additional information

here's the full error, but it doesn't hint at why sage is doing this:
```
[2021-04-16 21:10:07] production.ERROR: is_writable(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/srv/www/:/tmp) {"userId":28,"exception":"[object] (ErrorException(code: 0): is_writable(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/srv/www/:/tmp) at /srv/www/servername/releases/20210416210751/web/wp/wp-admin/includes/misc.php:266)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'is_writable(): ...', '/srv/www/into/r...', 266, Array)
#1 /srv/www/servername/releases/20210416210751/web/wp/wp-admin/includes/misc.php(266): is_writable('/')
#2 /srv/www/servername/releases/20210416210751/web/wp/wp-includes/class-wp-rewrite.php(1869): save_mod_rewrite_rules()
#3 /srv/www/servername/releases/20210416210751/web/wp/wp-includes/class-wp-hook.php(292): WP_Rewrite->flush_rules(true)
#4 /srv/www/servername/releases/20210416210751/web/wp/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#5 /srv/www/servername/releases/20210416210751/web/wp/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#6 /srv/www/servername/releases/20210416210751/web/wp/wp-settings.php(582): do_action('wp_loaded')
#7 /srv/www/servername/releases/20210416210751/web/wp-config.php(9): require_once('/srv/www/servername/r...')
#8 /srv/www/servername/releases/20210416210751/web/wp/wp-load.php(42): require_once('/srv/www/servername/r...')
#9 /srv/www/servername/releases/20210416210751/web/wp/wp-blog-header.php(13): require_once('/srv/www/servername/r...')
#10 /srv/www/servername/releases/20210416210751/web/index.php(6): require('/srv/www/servername/r...')
#11 {main}
"} 

```

**Comment by andriilive** [comment]
Faced same issue on OpenLightSpeed & Digitalocean
