### ISSUE TITLE
Sage10: build issue

### ISSUE THREAD

**Issue by kukac7** [roots/sage#2747]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

hi,

i've already deleted everything, updated it, but it throws this issue.
what could be the problem?
thanks!

`package.json`
```
{
	"private": true,
	"browserslist": [
		"extends @wordpress/browserslist-config"
	],
	"engines": {
		"node": ">=12.14.0"
	},
	"scripts": {
		"build": "mix",
		"build:production": "mix --production",
		"start": "mix watch",
		"hot": "mix watch --hot",
		"clear": "wp acorn optimize:clear",
		"test": "npm run lint",
		"lint": "npm run lint:js && npm run lint:css",
		"lint:js": "eslint resources/scripts",
		"lint:css": "stylelint \"resources/**/*.{css,scss,vue}\"",
		"translate": "npm run translate:pot && npm run translate:js",
		"translate:pot": "wp i18n make-pot . ./resources/lang/sage.pot --ignore-domain --include=\"app,resources\"",
		"translate:js": "wp i18n make-json ./resources/lang --pretty-print"
	},
	"devDependencies": {
		"@tailwindcss/typography": "^0.4.1",
		"@tinypixelco/laravel-mix-wp-blocks": "^1.1.0",
		"@wordpress/babel-preset-default": "^6.1.0",
		"@wordpress/browserslist-config": "^4.0.0",
		"@wordpress/dependency-extraction-webpack-plugin": "^3.1.3",
		"babel-eslint": "^10.1.0",
		"browser-sync": "^2.26.14",
		"browser-sync-webpack-plugin": "^2.3.0",
		"eslint": "^7.27.0",
		"eslint-plugin-import": "^2.23.3",
		"laravel-mix": "^6.0.19",
		"postcss": "^8.3.0",
		"sass": "^1.34.0",
		"sass-loader": "11.1.1",
		"stylelint": "^13.13.1",
		"stylelint-config-standard": "^22.0.0",
		"tailwindcss": "^2.1.2"
	},
	"peerDependencies": {
		"jquery": "^3.6.0"
	}
}
```

## Steps to reproduce

```
yarn build:production
yarn run v1.22.10
$ mix --production

● Mix █████████████████████████ building (43%)  
 import loader ./node_modules/sass-loader/dist/cjs.js

/xxx/wp-content/themes/sage/node_modules/postcss-loader/dist/index.js:102
    if (!hasExplicitDependencyOnPostCSS && processor.version.startsWith("7.")) {
                                                     ^

TypeError: Cannot read property 'version' of undefined
    at Object.loader (/xxx/wp-content/themes/sage/node_modules/postcss-loader/dist/index.js:102:54)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

## Versions

```
node -v
v16.3.0
```

```
npm -v
7.18.1
```

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by kukac7** [comment]
i also tried node 14 version.
npm, yarn cleaning.
it was also a restart.

```
npm run build:production

> @ build:production /xxx/public/wp-content/themes/xy
> mix --production


● Mix █████████████████████████ building (10%) 0/5 entries 5/6 dependencies 0/5 modules 5 active 
 css-loader › postcss-loader › sass-loader › resources/styles/editor.scss

(node:9175) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'version' of undefined
    at Object.loader (/xxx/public/wp-content/themes/xy/node_modules/postcss-loader/dist/index.js:102:54)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9175) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'version' of undefined
    at Object.loader (/xxx/public/wp-content/themes/xy/node_modules/postcss-loader/dist/index.js:102:54)
(node:9175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
