### ISSUE TITLE
Fatal error when the asset build hasn't yet ran, `public` directory not yet created

### ISSUE THREAD

**Issue by retlehs** [roots/sage#2852]
## Description

`yarn dev` or `yarn build` must be ran in order for WP to load

## Steps to reproduce

1. Clone repo/create a project with Composer
2. Activate the theme
3. See errors

**Expected behavior:** WP admin or front-end should load without errors

**Actual behavior:** WP admin/front-end won't load until the build is ran

**Reproduces how often:** Every time

```
Fatal error: Uncaught TypeError: Return value of Roots\Acorn\Bootloader::findPath() must be of the type string, null returned in /srv/www/example.com/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php:277 Stack trace: #0 /srv/www/example.com/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(247): Roots\Acorn\Bootloader->findPath('public') #1 /srv/www/example.com/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(205): Roots\Acorn\Bootloader->usePaths() #2 /srv/www/example.com/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(180): Roots\Acorn\Bootloader->app() #3 /srv/www/example.com/current/web/wp/wp-includes/class-wp-hook.php(303): Roots\Acorn\Bootloader->__invoke('') #4 /srv/www/example.com/current/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #5 /srv/www/example.com/current/web/wp/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #6 /srv/www/example.com/current/web/wp/wp-s in /srv/www/example.com/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php on line 277
```

**Comment by QWp6t** [comment]
This has been fixed in Acorn, but you'll still run into issues with it not finding the manifest. But that's a much clearer error.

**Comment by retlehs** [comment]
@QWp6t :+1: let's get the missing manifest error to be non-fatal

**Comment by strarsis** [comment]
I get this error also after a successful `build` run. Do I have to create the `public` directory manually to get around this (currently fatal) error?
