### ISSUE TITLE
Bug: Bud Build Failure on Yarn Dev TypeError: fsevents.watch is not a function

### ISSUE THREAD

**Issue by Mulegoat** [roots/sage#2879]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Tried a fresh install of the latest sage 10 but Yarn dev generates TypeError: fsevents.watch is not a function:
at createFSEventsInstance (/Users/../node_modules/@roots/bud-support/lib/cjs/index.js:10389:25)
at setFSEventsListener (/Users/../node_modules/@roots/bud-support/lib/cjs/index.js:10445:16)
at FsEventsHandler._watchWithFsEvents (/Users/../node_modules/@roots/bud-support/lib/cjs/index.js:10647:18)
at FsEventsHandler.initWatch (/Users/../node_modules/@roots/bud-support/lib/cjs/index.js:10723:23)
at FsEventsHandler._addToFsEvents (/Users/../node_modules/@roots/bud-support/lib/cjs/index.js:10812:12)

#### What have you tried?
Checking the output log of the terminal session

#### What insights have you gained?
Issue with node_modules/@roots/bud-support/lib/cjs/index.js:10389
  const stop = fsevents.watch(path, callback);

### Steps To Reproduce

1. NVM use 16.13.0 
2. Composer install sage
3. Add local URL to bud.config
4. Run Yarn dev

### Expected Behavior

Browser-sync session to start

### Actual Behavior

Building Bud doesn't complete. This is on a clean install, no additional packages added

### Relevant Log Output

```shell
From Terminal:

yarn run v1.22.10
$ bud dev
[ves] › ▶  bud          Initialized timer...
[ves] › ❯  process.env.NODE_ENV development
[ves] › ❯  process.env.BABEL_ENV development
▶  building bud Initialized timer...
[ves] › …  [1/5] bootstrap api
[ves] [api] › ❯  binding bud.alias facade
[ves] › ✔  bound alias
[ves] [api] › ✔  binding bud.alias facade
[ves] [api] › ❯  binding bud.assets facade
[ves] › ✔  bound assets
[ves] [api] › ✔  binding bud.assets facade
[ves] [api] › ❯  binding bud.copy facade
[ves] › ✔  bound copy
[ves] [api] › ✔  binding bud.copy facade
[ves] [api] › ❯  binding bud.config facade
[ves] › ✔  bound config
[ves] [api] › ✔  binding bud.config facade
[ves] [api] › ❯  binding bud.webpackConfig facade
[ves] › ✔  bound webpackConfig
[ves] [api] › ✔  binding bud.webpackConfig facade
[ves] [api] › ❯  binding bud.override facade
[ves] › ✔  bound override
[ves] [api] › ✔  binding bud.override facade
[ves] [api] › ❯  binding bud.define facade
[ves] › ✔  bound define
[ves] [api] › ✔  binding bud.define facade
[ves] [api] › ❯  binding bud.devtool facade
[ves] › ✔  bound devtool
[ves] [api] › ✔  binding bud.devtool facade
[ves] [api] › ❯  binding bud.entry facade
[ves] › ✔  bound entry
[ves] [api] › ✔  binding bud.entry facade
[ves] [api] › ❯  binding bud.js facade
[ves] › ✔  bound js
[ves] [api] › ✔  binding bud.js facade
[ves] [api] › ❯  binding bud.css facade
[ves] › ✔  bound css
[ves] [api] › ✔  binding bud.css facade
[ves] [api] › ❯  binding bud.experiments facade
[ves] › ✔  bound experiments
[ves] [api] › ✔  binding bud.experiments facade
[ves] [api] › ❯  binding bud.externals facade
[ves] › ✔  bound externals
[ves] [api] › ✔  binding bud.externals facade
[ves] [api] › ❯  binding bud.hash facade
[ves] › ✔  bound hash
[ves] [api] › ✔  binding bud.hash facade
[ves] [api] › ❯  binding bud.version facade
[ves] › ✔  bound version
[ves] [api] › ✔  binding bud.version facade
[ves] [api] › ❯  binding bud.minimize facade
[ves] › ✔  bound minimize
[ves] [api] › ✔  binding bud.minimize facade
[ves] [api] › ❯  binding bud.persist facade
[ves] › ✔  bound persist
[ves] [api] › ✔  binding bud.persist facade
[ves] [api] › ❯  binding bud.provide facade
[ves] › ✔  bound provide
[ves] [api] › ✔  binding bud.provide facade
[ves] [api] › ❯  binding bud.proxy facade
[ves] › ✔  bound proxy
[ves] [api] › ✔  binding bud.proxy facade
[ves] [api] › ❯  binding bud.run facade
[ves] › ✔  bound run
[ves] [api] › ✔  binding bud.run facade
[ves] [api] › ❯  binding bud.runtime facade
[ves] › ✔  bound runtime
[ves] [api] › ✔  binding bud.runtime facade
[ves] [api] › ❯  binding bud.serve facade
[ves] › ✔  bound serve
[ves] [api] › ✔  binding bud.serve facade
[ves] [api] › ❯  binding bud.splitChunks facade
[ves] › ✔  bound splitChunks
[ves] [api] › ✔  binding bud.splitChunks facade
[ves] [api] › ❯  binding bud.vendor facade
[ves] › ✔  bound vendor
[ves] [api] › ✔  binding bud.vendor facade
[ves] [api] › ❯  binding bud.template facade
[ves] › ✔  bound template
[ves] [api] › ✔  binding bud.template facade
[ves] [api] › ❯  binding bud.watch facade
[ves] › ✔  bound watch
[ves] [api] › ✔  binding bud.watch facade
[ves] › ✔  bound use
[ves] › ✔  bound setPublicPath
[ves] › ✔  bound publicPath
[ves] › …  [2/5] bootstrap hooks
[ves] › …  [3/5] bootstrap project
[ves] › …  [4/5] bootstrap env
[ves] [env] › ❯  loading env
[ves] [env] › ⚠  no env values found
[ves] › …  [5/5] bootstrap server
[ves] › ✔  [1/5] bootstrap api
[ves] › ✔  [2/5] bootstrap hooks
[ves] › ✔  [4/5] bootstrap env
[ves] › ✔  [5/5] bootstrap server
[ves] › ✔  [3/5] bootstrap project
[ves] › …  [1/5] register project
[ves] › …  [2/5] register build
[ves] › …  [3/5] register compiler
[ves] › …  [4/5] register dependencies
[ves] › …  [5/5] register server
[ves] › ✔  [3/5] register compiler
[ves] › ✔  [4/5] register dependencies
[ves] › ✔  [5/5] register server
[ves] › ✔  [2/5] register build
[ves] [project] › ▶  building profile Initialized timer...
[ves] [project] › …  analyzing dependencies
[ves] [project] › …  analyzing devDependencies
[ves] [project] › ✔  resolved @roots/sage ./node_modules/@roots/sage
[ves] [project] › ✔  manifest resolved @roots/sage
[ves] [project] › ✔  resolved @roots/bud-preset-wordpress ./node_modules/@roots/bud-preset-wordpress
[ves] [project] › ✔  resolved @roots/bud-eslint ./node_modules/@roots/bud-eslint
[ves] [project] › ✔  resolved @roots/bud-prettier ./node_modules/@roots/bud-prettier
[ves] [project] › ✔  resolved @roots/bud-stylelint ./node_modules/@roots/bud-stylelint
[ves] [project] › ✔  resolved @roots/bud-tailwindcss ./node_modules/@roots/bud-tailwindcss
[ves] [project] › ✔  manifest resolved @roots/bud-preset-wordpress
[ves] [project] › ✔  required peer dependency is met @wordpress/browserslist-config@4.1.0
[ves] [project] › ✔  manifest resolved @roots/bud-eslint
[ves] [project] › ✔  required peer dependency is met eslint@7.32.0
[ves] [project] › ✔  required peer dependency is met prettier@2.5.0
[ves] [project] › ✔  manifest resolved @roots/bud-prettier
[ves] [project] › ✔  manifest resolved @roots/bud-stylelint
[ves] [project] › ✔  manifest resolved @roots/bud-tailwindcss
[ves] [project] › ✔  required peer dependency is met tailwindcss@2.2.19
[ves] [project] › ✔  resolved @roots/bud-preset-recommend ./node_modules/@roots/bud-preset-recommend
[ves] [project] › ✔  resolved @roots/bud-react ./node_modules/@roots/bud-react
[ves] [project] › ✔  resolved @roots/bud-wordpress-externals ./node_modules/@roots/bud-wordpress-externals
[ves] [project] › ✔  resolved @roots/bud-wordpress-dependencies ./node_modules/@roots/bud-wordpress-dependencies
[ves] [project] › ✔  resolved @roots/bud-wordpress-manifests ./node_modules/@roots/bud-wordpress-manifests
[ves] [project] › ✔  resolved @roots/bud-postcss ./node_modules/@roots/bud-postcss
[ves] [project] › ✔  manifest resolved @roots/bud-preset-recommend
[ves] [project] › ✔  manifest resolved @roots/bud-react
[ves] [project] › ✔  required peer dependency is met react@17.0.2
[ves] [project] › ✔  required peer dependency is met react-dom@17.0.2
[ves] [project] › ✔  manifest resolved @roots/bud-wordpress-externals
[ves] [project] › ✔  manifest resolved @roots/bud-wordpress-manifests
[ves] [project] › ✔  manifest resolved @roots/bud-wordpress-dependencies
[ves] [project] › ✔  manifest resolved @roots/bud-postcss
[ves] [project] › ✔  required peer dependency is met postcss@8.4.4
[ves] [project] › ✔  required peer dependency is met postcss-import@14.0.2
[ves] [project] › ✔  required peer dependency is met postcss-nested@5.0.6
[ves] [project] › ✔  required peer dependency is met postcss-preset-env@7.0.1
[ves] [project] › ✔  resolved @roots/bud-babel ./node_modules/@roots/bud-babel
[ves] [project] › ✔  resolved @roots/bud-entrypoints ./node_modules/@roots/bud-entrypoints
[ves] [project] › ✔  manifest resolved @roots/bud-babel
[ves] [project] › ✔  manifest resolved @roots/bud-entrypoints
[ves] [project] › …  reading project configuration files
[ves] [project] › ●  located user config bud.config.js
[ves] [project] › ◼  building profile Timer run for: 55ms
[ves] › ✔  [1/5] register project
[ves] › …  [1/3] registered api
[ves] › …  [2/3] registered dashboard
[ves] › …  [3/3] registered extensions
[ves] [extensions] › ▶  instantiating built-ins Initialized timer...
[ves] [extensions] › ✔  webpack-provide-plugin instantiated
[ves] [extensions] › ✔  clean-webpack-plugin instantiated
[ves] [extensions] › ✔  copy-webpack-plugin instantiated
[ves] [extensions] › ✔  webpack-define-plugin instantiated
[ves] [extensions] › ✔  webpack-hot-module-replacement-plugin instantiated
[ves] [extensions] › ✔  ignore-emit-webpack-plugin instantiated
[ves] [extensions] › ✔  webpack-manifest-plugin instantiated
[ves] [extensions] › ✔  mini-css-extract-plugin instantiated
[ves] › ✔  [2/3] registered dashboard
[ves] › ✔  [1/3] registered api
[ves] [extensions] › ◼  instantiating built-ins Timer run for: 2ms
[ves] › ✔  [3/3] registered extensions
[ves] › …  [1/4] boot hooks
[ves] › …  [2/4] boot project
[ves] › …  [3/4] boot cache
[ves] › …  [4/4] boot extensions
[ves] [extensions] › ❯  extension injection enabled
[ves] [extensions] › …  injecting project extensions
[ves] › ✔  [1/4] boot hooks
[ves] › ✔  [2/4] boot project
[ves] [extensions] › ✔  @roots/sage resolved
[ves] [extensions] › ✔  @roots/bud-preset-wordpress resolved
[ves] [extensions] › ✔  eslint-webpack-plugin resolved
[ves] [extensions] › ✔  @roots/bud-prettier resolved
[ves] [extensions] › ✔  stylelint-webpack-plugin resolved
[ves] [extensions] › ✔  @roots/bud-tailwindcss resolved
[ves] [extensions] › ✔  @roots/bud-preset-recommend resolved
[ves] [extensions] › ✔  @roots/bud-react resolved
[ves] [extensions] › ✔  @roots/wordpress-externals-webpack-plugin resolved
[ves] [extensions] › ✔  @roots/bud-wordpress-manifests resolved
[ves] [extensions] › ✔  @roots/wordpress-dependencies-webpack-plugin resolved
[ves] [extensions] › ✔  @roots/bud-postcss resolved
[ves] [extensions] › ✔  @roots/bud-babel resolved
[ves] [extensions] › ✔  @roots/bud-entrypoints resolved
[ves] › ✔  [4/4] boot extensions
[ves] [cache] › ℹ  cache hash generated 1yq68pi6cecw0vqy1cnmiis05no_
[ves] [cache] › ℹ  cache feature flag: true
[ves] [cache] › ℹ  --cache flag: true
[ves] [cache] › ❯  --cache.type flag filesystem
[ves] [api] › ❯  executing persist ["filesystem"]
[ves] [api] › ✔  cache enabled filesystem
[ves] › ✔  [3/4] boot cache
[ves] › …  [1/2] booted build
[ves] › …  [2/2] booted extensions
[ves] [extensions] › ▶  registering  Initialized timer...
[ves] › ✔  [1/2] booted build
[ves] [extensions] › ✔  registered bud.eslint eslint-webpack-plugin
[ves] [extensions] › ✔  registered bud.postcss @roots/bud-postcss
[ves] [extensions] › ✔  registered bud.babel @roots/bud-babel
[ves] [extensions] › ✔  register called webpack-provide-plugin
[ves] [extensions] › ✔  register called clean-webpack-plugin
[ves] [extensions] › ✔  register called copy-webpack-plugin
[ves] [extensions] › ✔  register called webpack-define-plugin
[ves] [extensions] › ✔  register called webpack-hot-module-replacement-plugin
[ves] [extensions] › ✔  register called ignore-emit-webpack-plugin
[ves] [extensions] › ✔  register called webpack-manifest-plugin
[ves] [extensions] › ✔  register called mini-css-extract-plugin
[ves] [extensions] › ✔  register called @roots/sage
[ves] [extensions] › ✔  register called @roots/bud-preset-wordpress
[ves] [extensions] › ✔  register called @roots/bud-prettier
[ves] [extensions] › ✔  register called stylelint-webpack-plugin
[ves] › ✔  bound tailwind
[ves] [extensions] › ✔  register called @roots/bud-preset-recommend
[ves] [extensions] › ✔  register called @roots/bud-react
[ves] [extensions] › ✔  register called @roots/wordpress-externals-webpack-plugin
[ves] [extensions] › ✔  register called @roots/bud-wordpress-manifests
[ves] [extensions] › ✔  register called @roots/wordpress-dependencies-webpack-plugin
[ves] [extensions] › ✔  register called @roots/bud-entrypoints
[ves] [extensions] › ✔  register called eslint-webpack-plugin
[ves] [extensions] › ✔  register called @roots/bud-tailwindcss
[ves] [extensions] › ✔  register called @roots/bud-babel
[ves] › ✔  postcss is installed
[ves] [@roots/bud-postcss] › …  resolving postcss plugins
[ves] [@roots/bud-postcss] › ✔  resolving postcss plugins
[ves] [extensions] › ✔  register called @roots/bud-postcss
[ves] [extensions] › ◼  registering  Timer run for: 43ms
[ves] [extensions] › ▶  booting      Initialized timer...
[ves] [api] › ❯  facade called: alias [{"@fonts":"./resources/fonts","@images":"[secure]/resources/images","@scripts":"[secure]/resources/scripts","@styles":"[secure]/resources/styles"}]
[ves] [api] › ❯  facade added to queue: alias [{"@fonts":"./resources/fonts","@images":"[secure]/resources/images","@scripts":"[secure]/resources/scripts","@styles":"[secure]/resources/styles"}]
[ves] [api] › ❯  facade called: provide [{"$":["jquery"],"jQuery":["jquery"]}]
[ves] [api] › ❯  facade added to queue: provide [{"$":["jquery"],"jQuery":["jquery"]}]
[ves] [api] › ❯  facade called: minimize []
[ves] [api] › ❯  facade added to queue: minimize []
[ves] [api] › ❯  facade called: hash []
[ves] [api] › ❯  facade added to queue: hash []
[ves] [api] › ❯  facade called: runtime ["single"]
[ves] [api] › ❯  facade added to queue: runtime ["single"]
[ves] [extensions] › ✔  @roots/sage booted
[ves] [api] › …  Executing 5 enqueued functions
[ves] [api] › ❯  executing alias [{"@fonts":"./resources/fonts","@images":"[secure]/resources/images","@scripts":"[secure]/resources/scripts","@styles":"[secure]/resources/styles"}]
[ves] [api] › ✔  alias @fonts ./resources/fonts
[ves] [api] › ✔  alias @images ./resources/images
[ves] [api] › ✔  alias @scripts ./resources/scripts
[ves] [api] › ✔  alias @styles ./resources/styles
[ves] [api] › ❯  executing provide [{"$":["jquery"],"jQuery":["jquery"]}]
[ves] [api] › ❯  executing minimize none
[ves] [api] › ❯  executing hash none
[ves] [api] › ✔  file hashing enabled
[ves] [api] › ❯  executing runtime ["single"]
[ves] › ✔  loaded user tailwindcss config from [secure]/tailwind.config.js
[ves] [extensions] [tailwindcss] › ✔  postcss has been configured for tailwindcss
[ves] › ✔  bound reactRefresh
[ves] [extensions] › ✔  @roots/bud-tailwindcss booted
[ves] [extensions] › ✔  register called @pmmmwh/react-refresh-webpack-plugin
[ves] [extensions] › ✔  @roots/bud-react booted
[ves] [extensions] › ◼  booting      Timer run for: 339ms
[ves] › ✔  [2/2] booted extensions
[ves] › ◼  building bud Timer run for: 968ms
[ves] [serve] › runner ✔  framework ready
[ves] [serve] › ▶  process user configs Initialized timer...
[ves] [serve] › ❯  processing [secure]/bud.config.js
[ves] [serve] › …  importing module [secure]/bud.config.js
[ves] [serve] › …  calling user config [secure]/bud.config.js
[ves] [api] › ❯  facade called: entry [{"app":["scripts/app.js","styles/app.css"],"editor":["scripts/editor.js","styles/editor.css"],"customizer":"scripts/customizer.js"}]
[ves] [api] › ❯  facade added to queue: entry [{"app":["scripts/app.js","styles/app.css"],"editor":["scripts/editor.js","styles/editor.css"],"customizer":"scripts/customizer.js"}]
[ves] [api] › ❯  facade called: assets [["resources/images"]]
[ves] [api] › ❯  facade added to queue: assets [["resources/images"]]
[ves] [api] › ❯  facade called: watch [["tailwind.config.js","resources/views/*.blade.php","app/View/**/*.php"]]
[ves] [api] › ❯  facade added to queue: watch [["tailwind.config.js","resources/views/*.blade.php","app/View/**/*.php"]]
[ves] [api] › ❯  facade called: proxy [{"target":"http://vanellensheryn.test"}]
[ves] [api] › ❯  facade added to queue: proxy [{"target":"http://vanellensheryn.test"}]
[ves] [api] › …  Executing 4 enqueued functions
[ves] [api] › ❯  executing entry [{"app":["scripts/app.js","styles/app.css"],"editor":["scripts/editor.js","styles/editor.css"],"customizer":"scripts/customizer.js"}]
[ves] [api] › ❯  executing assets [["resources/images"]]
[ves] [api] › ❯  executing watch [["tailwind.config.js","resources/views/*.blade.php","app/View/**/*.php"]]
[ves] [api] › ✔  watch files added tailwind.config.js, resources/views/*.blade.php, app/View/**/*.php
[ves] [api] › ❯  executing proxy [{"target":"http://vanellensheryn.test"}]
[ves] [serve] › ◼  process user configs Timer run for: 25ms
[ves] [api] › ❯  executing run [[]]
[ves] › ❯  event.build.make.promise api calls
[ves] › ℹ  glob search ["scripts/app.js","styles/app.css"]
[ves] › ℹ  glob directory [secure]/resources
[ves] › ℹ  glob results ["scripts/app.js","styles/app.css"]
[ves] [api] › ✔  entrypoints added app {"import":["scripts/app.js","styles/app.css"]}
[ves] › ℹ  glob search ["scripts/editor.js","styles/editor.css"]
[ves] › ℹ  glob directory [secure]/resources
[ves] › ℹ  glob results ["scripts/editor.js","styles/editor.css"]
[ves] [api] › ✔  entrypoints added editor {"import":["scripts/editor.js","styles/editor.css"]}
[ves] › ℹ  glob search ["scripts/customizer.js"]
[ves] › ℹ  glob directory [secure]/resources
[ves] › ℹ  glob results ["scripts/customizer.js"]
[ves] [api] › ✔  entrypoints added customizer {"import":["scripts/customizer.js"]}
[ves] [extensions] › ▶  extensions.make Initialized timer...
[ves] [extensions] › ✔  webpack-provide-plugin will be used in the compilation
[ves] [extensions] › ✔  clean-webpack-plugin will be used in the compilation
[ves] [extensions] › ❯  copy-webpack-plugin will not be used in the compilation
[ves] [extensions] › ❯  webpack-define-plugin will not be used in the compilation
[ves] [extensions] › ✔  webpack-hot-module-replacement-plugin will be used in the compilation
[ves] [extensions] › ✔  ignore-emit-webpack-plugin will be used in the compilation
[ves] [extensions] › ✔  webpack-manifest-plugin will be used in the compilation
[ves] [extensions] › ❯  mini-css-extract-plugin will not be used in the compilation
[ves] [extensions] › ✔  eslint-webpack-plugin will be used in the compilation
[ves] [extensions] › ✔  stylelint-webpack-plugin will be used in the compilation
[ves] [extensions] › ✔  @roots/wordpress-externals-webpack-plugin will be used in the compilation
[ves] [extensions] › ✔  @roots/bud-wordpress-manifests will be used in the compilation
[ves] [extensions] › ✔  @roots/wordpress-dependencies-webpack-plugin will be used in the compilation
[ves] [extensions] › ✔  @roots/bud-entrypoints will be used in the compilation
[ves] [extensions] › ✔  @pmmmwh/react-refresh-webpack-plugin will be used in the compilation
[ves] [extensions] › ◼  extensions.make Timer run for: 51ms
[ves] [build] › ⚠  build.make: excluding experiments value is undefined
[ves] [build] › ⚠  build.make: excluding externals value is undefined
[ves] [build] › ⚠  build.make: excluding profile value is undefined
[ves] [build] › ⚠  build.make: excluding stats value is undefined
[ves] [build] › ⚠  build.make: excluding watch value is undefined
[ves] [build] › ⚠  build.make: excluding watchOptions value is undefined
[ves] [project] › ✔  writing profile to disk ./.budfiles/bud/profile.json
[ves] [build] › ℹ  writing webpack dump to disk ./.budfiles/bud/webpack.config.js
[ves] › ℹ  using config from parent compiler
[ves] [dashboard] › ✔  rendering dashboard
[ves] › ◼  bud          Timer run for: 1.39s
[ves] [server] › ❯  middleware dev is enabled.
[ves] [server] › ❯  middleware hot is enabled.
[ves] [server] › ❯  middleware proxy is enabled.
[ves] [server] › ℹ  configured middleware: dev
[ves] [server] › ℹ  configured middleware: hot
[ves] [server] › ℹ  [HPM] Proxy created: /  -> http://vanellensheryn.test
[ves] [server] › ℹ  configured middleware: proxy
[ves] [server] › ✔  listening on port 3000



 dev: http://localhost:3000
 proxy target: http://vanellensheryn.test

 🆀 to exit

[ves] [server] › ❯  watching [secure]/tailwind.config.js for changes
[ves] [server] › ❯  watching [secure]/resources/views/404.blade.php for changes
[ves] [server] › ❯  watching [secure]/resources/views/index.blade.php for changes

 ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉

 building

 dev: http://localhost:3000
 proxy target: http://vanellensheryn.test

<i> [webpack-dev-middleware] wait until bundle finished: /browser-sync/socket.io/?EIO=3&transport=polling&t=NsKfkX9
/Users/marcoterrinoni/Sites/vanellensheryn/wp/wp-content/themes/ves/node_modules/@roots/bud-support/lib/cjs/index.js:10389
  const stop = fsevents.watch(path, callback);
                        ^

TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Users/marcoterrinoni/Sites/vanellensheryn/wp/wp-content/themes/ves/node_modules/@roots/bud-support/lib/cjs/index.js:10389:25)
    at setFSEventsListener (/Users/marcoterrinoni/Sites/vanellensheryn/wp/wp-content/themes/ves/node_modules/@roots/bud-support/lib/cjs/index.js:10445:16)
    at FsEventsHandler._watchWithFsEvents (/Users/marcoterrinoni/Sites/vanellensheryn/wp/wp-content/themes/ves/node_modules/@roots/bud-support/lib/cjs/index.js:10647:18)
    at FsEventsHandler.initWatch (/Users/marcoterrinoni/Sites/vanellensheryn/wp/wp-content/themes/ves/node_modules/@roots/bud-support/lib/cjs/index.js:10723:23)
    at FsEventsHandler._addToFsEvents (/Users/marcoterrinoni/Sites/vanellensheryn/wp/wp-content/themes/ves/node_modules/@roots/bud-support/lib/cjs/index.js:10812:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

From Yarn Error Log:
Trace: 
  Error: connect ENETUNREACH 104.16.26.35:443 - Local (0.0.0.0:50265)
      at internalConnect (node:net:931:16)
      at defaultTriggerAsyncIdScope (node:internal/async_hooks:454:18)
      at emitLookup (node:net:1075:9)
      at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:107524:28
      at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:107433:13
      at RawTask.module.exports.RawTask.call (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:83614:19)
      at flush (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:83696:29)
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at processImmediate (node:internal/timers:437:9)
```

### Versions

Sage 10.0.0-beta-2, Node 16.13.0, Composer 1.10.15, macOS Monterey 12.0.1

**Comment by retlehs** [comment]
i think this is resolved with recent updates to bud/sage 

try using [v5.0.0-next.19](https://github.com/roots/sage/pull/2895) and make sure you have https://github.com/roots/sage/pull/2890 in place as well

please start a topic over at https://discourse.roots.io/ if you're still having issues!

**Comment by Mulegoat** [comment]
Thanks Ben,

I've cloned the latest beta version and run yarn but am getting the following error:

error An unexpected error occurred: "https://registry.yarnpkg.com/@roots/bud-api/-/bud-api-5.0.0-next.19.tgz: Request failed \"503 Service Unavailable\""

Yarn Error Log:
Trace: 
  Error: https://registry.yarnpkg.com/@roots/bud-api/-/bud-api-5.0.0-next.19.tgz: Request failed "503 Service Unavailable"
      at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:696:66)
      at new ResponseError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:67058:16)
      at Request.emit (node:events:390:28)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141626:10)
      at ClientRequest.emit (node:events:390:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
      at TLSSocket.socketOnData (node:_http_client:487:22)
      at TLSSocket.emit (node:events:390:28)

Hope this helps

**Comment by Mulegoat** [comment]
I'll try again later on and if there's still a problem I'll post something on Discourse
