### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by wontone18** [roots/sage#3077]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

Hi

i installed this package in my testing project but when i am running the yarn i am getting this error

[TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
themes\sage\node_modules\graceful-fs\graceful-fs.js:118:14)](url)

### Steps To Reproduce

1. Install the basic theme from the package by using the composer.
2. Then node_module (all ref modules)
3. but running yarn dev its not creating the package.json file and i am getting the error.

### Expected Behavior

it should run the default theme

### Actual Behavior

error coming in node_modules

### Relevant Log Output

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readFile (node:fs:393:10)
    at go$readFile (D:\web\htdocs\wontonee\wp-content\themes\sage\node_modules\graceful-fs\graceful-fs.js:118:14)
    at readFile (D:\web\htdocs\wontonee\wp-content\themes\sage\node_modules\graceful-fs\graceful-fs.js:115:12)
    at D:\web\htdocs\wontonee\wp-content\themes\sage\node_modules\universalify\index.js:8:12
    at new Promise (<anonymous>)
    at readFile (D:\web\htdocs\wontonee\wp-content\themes\sage\node_modules\universalify\index.js:7:14)
    at Object._readFile (D:\web\htdocs\wontonee\wp-content\themes\sage\node_modules\jsonfile\index.js:19:58)
    at Object._readFile (D:\web\htdocs\wontonee\wp-content\themes\sage\node_modules\universalify\index.js:21:45)
    at Manifest.read (file:///D:/web/htdocs/wontonee/wp-content/themes/sage/node_modules/@roots/bud/lib/context/manifest.js:22:25)
    at makeContext (file:///D:/web/htdocs/wontonee/wp-content/themes/sage/node_modules/@roots/bud/lib/context/index.js:23:47) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Versions

windows 10

**Comment by retlehs** [comment]
it looks like you're running build commands on windows but not within the WSL environment? WSL is required to run sage/bud on windows as noted in the docs

github issues are meant for bug reports, so please head over to https://discourse.roots.io/ to create a support topic

**Comment by dendihandian** [comment]
oh no, this is disaster.

**Comment by retlehs** [comment]
@dendihandian no sir, i think you're lost — this is a lovely saturday morning. have a good one 😄
